### ISSUE TITLE
Can you please implement the "options" attribute?

### ISSUE THREAD

**Issue by AmitMY** [luisfarzati/ng-bs-daterangepicker#103]
The regular datepicker has options in the setup.
Can you do it as an attribute?
Like: `options="{singleDatePicker: true, showDropdowns: true}"`

**Comment by ramilani12** [comment]
I´ve just implemented this idea:

```
var options = {} 
var extendedOptions = $parse($attributes.options)($scope);
options = angular.merge(extendedOptions,options);
```
