### ISSUE TITLE
Version 0.0.5 to NPM

### ISSUE THREAD

**Issue by AmitMY** [luisfarzati/ng-bs-daterangepicker#115]
Please add version 0.0.5 to NPM.

**Comment by pvnr0082t** [comment]
@luisfarzati Same issue. Please publish the  latest version to NPM. Thanks you. :+1: 

https://github.com/cdnjs/cdnjs/issues/7802

**Comment by lukeaskew** [comment]
FWIW you can add the unpublished version by declaring the dependency like:

```
"ng-bs-daterangepicker": "github:luisfarzati/ng-bs-daterangepicker#v0.0.5"
```
