### ISSUE TITLE
"opens" attribute

### ISSUE THREAD

**Issue by mingos777** [luisfarzati/ng-bs-daterangepicker#23]
The current implementation of support for the "opens" option is this:

```
options.opens = $attributes.opens && $parse($attributes.opens)($scope);
```

This implies that the attribute's value must be a scope variable; simply adding `opens="left"` resolved to `undefined` and is silently ignored by the datepicker plugin.

I think it should be:

```
options.opens = $attributes.opens || "right";
```

This allows the use of a simple string, defaulting to "right".

**Comment by alanjames1987** [comment]
This seems to have been fixed in 0.0.4.
