### ISSUE TITLE
Fix naming of module and directive so that it can be used in more complex projects

### ISSUE THREAD

**Issue by cstephe** [luisfarzati/ng-bs-daterangepicker#27]
I like what I'm seeing so far but there are a few things that make it impossible for me to use it in a project i'm working on.  These are things that I wouldn't want to change on my own since they are the identify of the project.

A few naming changes need to be made in order for this module to be production ready. 

1. The name of the module itself is ngBootstrap it is neither a google module nor represents bootstrap.  

2. #20 show the directive being to greedy and attempting to bind to every input (even though it does try to bail on the binding) you can make it bind to type of daterange and restrict it to input

return {
                require: ['?:input'],
                restrict: 'A',
            };

**Comment by alanjames1987** [comment]
I believe your second point has been solved. The module seems to no longer bind to all input fields, only those with `type="daterange"`.

I also agree with the naming of the module. Please refer to issue #17 to discuss possible names. I am willing to change it in the very near future.
