### ISSUE TITLE
ability to fast jump through years and months

### ISSUE THREAD

**Issue by devmondo** [luisfarzati/ng-bs-daterangepicker#3]
hi, 
right now it is really tedious if i want to go from year 2013 to to year 1980, i have to keep pressing the previous button until i reach it, i think you would agree with me that it is not user friendly, and sorry if i sound harsh :)

here is an example where you get a menu to select a year

http://demos.kendoui.com/web/calendar/index.html

thanks in advanced.

**Comment by cyc1ingsir** [comment]
Thanks for referencing mvancamp's solution. It would be very useful if this addition found it's way back into the main version
