### ISSUE TITLE
onFocus event on the text field does not popup the date range.

### ISSUE THREAD

**Issue by Ajth** [luisfarzati/ng-bs-daterangepicker#30]
Hi,
In my UI  I have a calendar icon on which on-click event should popup the date range popup. I tried the onFocus on the date textfield when clicked on the icon but it does not popup the calendar.
Please help.

Thanks
Ajith

**Comment by alanjames1987** [comment]
The ng-bs-daterangepicker currently only supports `input` fields with `type="daterange"`. 

If you want this to function differently please submit a pull request and I will gladly accept it.

**Comment by alanjames1987** [comment]
Additionally this module can be triggered on any element by surrounding that element with a `label` tag which has a `for` to the input field of the daterangepicker.
