### ISSUE TITLE
Cancel resets to today's date

### ISSUE THREAD

**Issue by jmazin** [luisfarzati/ng-bs-daterangepicker#40]
Hi!  Thx for your work-- it's certainly appreciated.  I've noticed that if you click 'cancel' the first time the picker loads, the dates will reset (in the picker) to today's date -- you can reproduce it in your demo to see what I mean.  I'd like to help solve this issue but not sure how to go about it.

**Comment by arcadeJHS** [comment]
Hi!
Maybe this issue is closed, but I run in the same problem!
I solved it modifying the code in the change watcher:

```
			$scope.$watch($attributes.ngModel, function (modelValue) {
				if (!modelValue || (!modelValue.startDate)) {
					ngModel.$setViewValue({ startDate: moment().startOf('day'), endDate: moment().startOf('day') });
					return;
				}
				$element.data('daterangepicker').setStartDate(modelValue.startDate);
				$element.data('daterangepicker').setEndDate(modelValue.endDate);
				
				$element.data('daterangepicker').updateView();
				$element.data('daterangepicker').updateCalendars();
				$element.data('daterangepicker').updateInputText();
			});
```

setStartDate and setEndDate in fact also replace the "old" stored value.
