### ISSUE TITLE
$element.daterangepicker is not a function

### ISSUE THREAD

**Issue by harssh** [luisfarzati/ng-bs-daterangepicker#62]
.link@http://localhost:3000/lib/ng-bs-daterangepicker-plus/src/ng-bs-daterangepicker.js:54
nodeLinkFn@http://localhost:3000/lib/angular/angular.js:6753
compositeLinkFn@http://localhost:3000/lib/angular/angular.js:6146
compositeLinkFn@http://localhost:3000/lib/angular/angular.js:6149
compositeLinkFn@http://localhost:3000/lib/angular/angular.js:6149
compositeLinkFn@http://localhost:3000/lib/angular/angular.js:6149
compositeLinkFn@http://localhost:3000/lib/angular/angular.js:6149
compositeLinkFn@http://localhost:3000/lib/angular/angular.js:6149

**Comment by alanjames1987** [comment]
You must include [Dan Grossman's bootstrap-daterangepicker](https://github.com/dangrossman/bootstrap-daterangepicker) above the script tag for ng-bs-daterangepicker.

If this is still an issue please comment back, but I am closing this for now.

**Comment by w2iktor** [comment]
Hi,

I'm using Require.js to load ng-bs-datepicker (v0.0.5) and randomly get the same error:
```
angular.min.js:116 TypeError: $element.daterangepicker is not a function
    at link (http://localhost:8080/assets/libs/ng-bs-daterangepicker.js:86:15)
```
Require.js has possibility to order loading modules by dependency mechanism:
```
'daterangepicker': ['moment', 'jquery', 'bootstrap'],
'ng-bs-daterangepicker': ['angular', 'daterangepicker', 'moment', 'jquery', 'bootstrap']
```
and I suppose that generated links order is correct:
```
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="daterangepicker" src="app/components/../../assets/libs/daterangepicker.js"></script>
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="ng-bs-daterangepicker" src="app/components/../../assets/libs/ng-bs-daterangepicker.js"></script>
```
however every third (on average - it's randomly) load has result in above error.

Can you please help me in investigation?

**Comment by mileydevlin** [comment]
Hello,

 I am having same problem as w2iktor. w2iktor did you manage to get this resolved ?

Thanks in advance
Miley

**Comment by carlosamn** [comment]
Hi,
I have a similar issue, I am tired of try a lot of links and scrips on my <head>, but It doesn't recognize the function daterangepicker, It is my function:
<script type="text/javascript">
$(function() {
    var start = moment().subtract(29, 'days');
    var end = moment();
    function cb(start, end) {
        $('#reportrange').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
    $('#reportrange').daterangepicker(cb);
    cb(start, end);
    });
</script> 

On my index:
<div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
    <span></span> <b class="caret"></b>
</div>

My head:

<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />
 <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

Can anyone can help me please
