### ISSUE TITLE
Calendar is not well rendered in firefox

### ISSUE THREAD

**Issue by rbecheras** [luisfarzati/ng-bs-daterangepicker#65]
In chrome : http://postimg.org/image/ylrrubua1

In firefox : http://postimg.org/image/4id92dr0p

**Comment by alanjames1987** [comment]
This is an issue with Dan Grossman's bootstrap-daterangepicker which this module is based on. This module does not change CSS.

Please refer to [Dan's repo](https://github.com/dangrossman/bootstrap-daterangepicker) for more information. It should be solved in his project and not this one.

**Comment by rbecheras** [comment]
Thanks @alanjames1987
