### ISSUE TITLE
Conflict with ui-select

### ISSUE THREAD

**Issue by lukaszgrolik** [luisfarzati/ng-bs-daterangepicker#70]
When I use ng-bs-daterangepicker, all my ui-selects throw `ngModel, required by directive 'input', can't be found!` See this issue: https://github.com/angular-ui/ui-select/issues/526

**Comment by cojack** [comment]
This is because he make something strange with dist/ng-bs-daterangepicker.min.js there is not ? before ngModel, use src/ng-bs-daterangepicker.js and it works well.

**Comment by luisfarzati** [comment]
There are a few things that you'll find disgusting, as this was one of my first Angular projects. Naming the module with the ng prefix is one of those anti-practices. Fortunately @timdockins and @alanjames1987 will reactivate this project and make things right!
