### ISSUE TITLE
Update to 0.0.4 or 0.1.0

### ISSUE THREAD

**Issue by alanjames1987** [luisfarzati/ng-bs-daterangepicker#73]
There are some features that have been added to master that are not currently part of 0.0.3. It looks like it has also been over a year since the version number was updated so I'm guessing at some point it was intended to be.

For example, `locale` as part of the options is now supported, but the master branch containing this has not been tagged.

https://github.com/luisfarzati/ng-bs-daterangepicker/blob/master/src/ng-bs-daterangepicker.js#L23

Do you know when you are releasing 0.0.4 or 0.1.0? I don't know which version you consider more apt.

**Comment by luisfarzati** [comment]
Sorry, I just have been merging a few PRs but I don't really have time to maintain this project any longer. See #63. If anybody's willing to jump in, I'll happily grant access. I can also point this project to a fork if there's someone who's keeping the project alive.

**Comment by alanjames1987** [comment]
That's fair. I would be willing to make changes and help maintain but I don't have much free time myself.

**Comment by timdockins** [comment]
Hi there!  Finding time to devote to it has been difficult for me too.  I had started to go through the issues and PRs, but got side-tracked.  Awesome that you got some done, Luis.

Perhaps we can have a joint effort?

**Comment by alanjames1987** [comment]
I will be using this library at the company I work for and can make updates and can for sure make updates as it relates to my work here.

If you give me access I will start solving issues and accepting pull requests as best I can.

**Comment by luisfarzati** [comment]
That's great to hear. Thank you! Please feel free to make any changes you consider necessary. @timdockins was willing to contribute as well.

**Comment by alanjames1987** [comment]
I have made merged in all the pull requests, made some changes, made sure all the tests pass, and tagged the release as 0.0.4. 

I will probably be making more changes as I spot them.
