### ISSUE TITLE
How to use ranges?

### ISSUE THREAD

**Issue by divan** [luisfarzati/ng-bs-daterangepicker#75]
Hi,

I want to use 'ranges' functionality and there is seems to be some mismatch in docs on format of ranges json. In README sample ranges looks like:
```javascript
ranges="{'Special Range':{'startDate': '2013-09-2', 'endDate': '2013-09-5'}}">
```

while on the demo page it's

```javascript
ranges = {
	'Today': [moment(), moment()],
	'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
	'Last 7 days': [moment().subtract('days', 7), moment()],
	'Last 30 days': [moment().subtract('days', 30), moment()],
	'This month': [moment().startOf('month'), moment().endOf('month')]
}
```
So, range should be specified as an array or as an object?

Moreover, in README it's written that ranges specified via 'ranges' attr, but in the demo, "options='range'" is used. Which one is correct?

Anyway, I can't make it work (ranges displayed, but on selection I always get today-today pair), but before digging deeper, I want to understand how is it supposed to work in the first place.

Thanks in advance.

**Comment by alanjames1987** [comment]
In my experience the `ranges` variable should be an object which keys are a label for the range. The key's value can either be arrays of two date values, or an object with the property of `startDate` and `endDate`.

It should be applied to the HTML using the `range` attribute.

```html
...ranges="{'Special Range':{'startDate': '2013-09-2', 'endDate': '2013-09-5'}}">
```

```js
ranges = {
    'Today': [moment(), moment()],
    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
    'Last 7 days': [moment().subtract('days', 7), moment()],
    'Last 30 days': [moment().subtract('days', 30), moment()],
    'This month': [moment().startOf('month'), moment().endOf('month')]
}
```

 Additionally I have updated the example code shown in the pre tag. It was using `options` and was incorrect.

**Comment by divan** [comment]
Thank you.
